In [2]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
aids_clinical_trials_group_study_175 = fetch_ucirepo(id=890) 
  
# data (as pandas dataframes) 
X = aids_clinical_trials_group_study_175.data.features 
y = aids_clinical_trials_group_study_175.data.targets 
  
# metadata 
print(aids_clinical_trials_group_study_175.metadata) 
  
# variable information 
print(aids_clinical_trials_group_study_175.variables)

{'uci_id': 890, 'name': 'AIDS Clinical Trials Group Study 175', 'repository_url': 'https://archive.ics.uci.edu/dataset/890/aids+clinical+trials+group+study+175', 'data_url': 'https://archive.ics.uci.edu/static/public/890/data.csv', 'abstract': 'The AIDS Clinical Trials Group Study 175 Dataset contains healthcare statistics and categorical information about patients who have been diagnosed with AIDS. This dataset was initially published in 1996. The prediction task is to predict whether or not each patient died within a certain window of time or not. ', 'area': 'Health and Medicine', 'tasks': ['Classification', 'Regression'], 'characteristics': ['Tabular', 'Multivariate'], 'num_instances': 2139, 'num_features': 23, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Age', 'Sexual Orientation', 'Race', 'Gender'], 'target_col': ['cid'], 'index_col': ['pidnum'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1996, 'last_updated': 'Fri Nov 03 2023', 'dataset_doi': '10.24432/C5ZG8F', 'creators': ['S. Hammer', 'D. Katzenstein', 'M. Hughes', 'H. Gundacker', 'R. Schooley', 'R. Haubrich', 'W. K.', 'M. Lederman', 'J. Phair', 'M. Niu', 'M. Hirsch', 'T. Merigan'], 'intro_paper': {'ID': 307, 'type': 'NATIVE', 'title': 'A trial comparing nucleoside monotherapy with combination therapy in HIV-infected adults with CD4 cell counts from 200 to 500 per cubic millimeter. AIDS Clinical Trials Group Study 175 Study Team.', 'authors': 'S. Hammer, D. Katzenstein, M. Hughes, H. Gundacker, R. Schooley, R. Haubrich, W. K. Henry, M. Lederman, J. Phair, M. Niu, M. Hirsch, T. Merigan', 'venue': 'New England Journal of Medicine', 'year': 1996, 'journal': None, 'DOI': None, 'URL': 'https://www.semanticscholar.org/paper/c7c401dd7d49ead07e70b299e422b27314589d2f', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': None, 'purpose': 'To examine the performance of two different types of AIDS treatments', 'funded_by': '- AIDS Clinical Trials Group of the National Institute of Allergy and Infectious Diseases\n- General Research Center units funded by the National Center for Research Resources', 'instances_represent': '- Health records\n- AIDS patients\n- US only', 'recommended_data_splits': 'Cross validation or a single train-test split could be used.', 'sensitive_data': '- Ethnicity (race)\n- Gender', 'preprocessing_description': 'No', 'variable_info': '- Personal information (age, weight, race, gender, sexual activity)\n- Medical history (hemophilia, history of IV drugs)\n- Treatment history (ZDV/non-ZDV treatment history)\n- Lab results (CD4/CD8 counts)', 'citation': None}, 'external_url': 'https://classic.clinicaltrials.gov/ct2/show/NCT00000625'}
       name     role        type         demographic  \
0    pidnum       ID     Integer                None
1       cid   Target      Binary                None
2      time  Feature     Integer                None
3       trt  Feature     Integer                None
4       age  Feature     Integer                 Age
5      wtkg  Feature  Continuous                None
6      hemo  Feature      Binary                None
7      homo  Feature      Binary  Sexual Orientation
8     drugs  Feature      Binary                None
9    karnof  Feature     Integer                None
10   oprior  Feature      Binary                None
11      z30  Feature      Binary                None
12   zprior  Feature      Binary                None
13  preanti  Feature     Integer                None
14     race  Feature     Integer                Race
15   gender  Feature      Binary              Gender
16     str2  Feature      Binary                None
17    strat  Feature     Integer                None
18  symptom  Feature      Binary                None
19    treat  Feature      Binary                None
20   offtrt  Feature      Binary                None
21     cd40  Feature     Integer                None
22    cd420  Feature     Integer                None
23     cd80  Feature     Integer                None
24    cd820  Feature     Integer                None

                                          description units missing_values
0                                          Patient ID  None             no
1    censoring indicator (1 = failure, 0 = censoring)  None             no
2                        time to failure or censoring  None             no
3   treatment indicator (0 = ZDV only; 1 = ZDV + d...  None             no
4                               age (yrs) at baseline  None             no
5                             weight (kg) at baseline  None             no
6                            hemophilia (0=no, 1=yes)  None             no
7                   homosexual activity (0=no, 1=yes)  None             no
8                history of IV drug use (0=no, 1=yes)  None             no
9               Karnofsky score (on a scale of 0-100)  None             no
10  Non-ZDV antiretroviral therapy pre-175 (0=no, ...  None             no
11      ZDV in the 30 days prior to 175 (0=no, 1=yes)  None             no
12                     ZDV prior to 175 (0=no, 1=yes)  None             no
13             # days pre-175 anti-retroviral therapy  None             no
14                        race (0=White, 1=non-white)  None             no
15                                  gender (0=F, 1=M)  None             no
16    antiretroviral history (0=naive, 1=experienced)  None             no
17  antiretroviral history stratification (1='Anti...  None             no
18            symptomatic indicator (0=asymp, 1=symp)  None             no
19         treatment indicator (0=ZDV only, 1=others)  None             no
20  indicator of off-trt before 96+/-5 weeks (0=no...  None             no
21                                    CD4 at baseline  None             no
22                                CD4 at 20+/-5 weeks  None             no
23                                    CD8 at baseline  None             no
24                                CD8 at 20+/-5 weeks  None             no

In [3]:
import pandas as pd

df_features = pd.DataFrame(X)
df_target = pd.DataFrame(y)

df = pd.concat([df_features, df_target], axis=1)
df

,time,trt,age,wtkg,hemo,homo,drugs,karnof,oprior,z30,...,str2,strat,symptom,treat,offtrt,cd40,cd420,cd80,cd820,cid
0,948,2,48,89.8128,0,0,0,100,0,0,...,0,1,0,1,0,422,477,566,324,0
1,1002,3,61,49.4424,0,0,0,90,0,1,...,1,3,0,1,0,162,218,392,564,1
2,961,3,45,88.4520,0,1,1,90,0,1,...,1,3,0,1,1,326,274,2063,1893,0
3,1166,3,47,85.2768,0,1,0,100,0,1,...,1,3,0,1,0,287,394,1590,966,0
4,1090,0,43,66.6792,0,1,0,100,0,1,...,1,3,0,0,0,504,353,870,782,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2134,1091,3,21,53.2980,1,0,0,100,0,1,...,1,3,0,1,1,152,109,561,720,0
2135,395,0,17,102.9672,1,0,0,100,0,1,...,1,3,0,0,1,373,218,1759,1030,0
2136,1104,2,53,69.8544,1,1,0,90,0,1,...,1,3,0,1,0,419,364,1391,1041,0
2137,465,0,14,60.0000,1,0,0,100,0,0,...,0,1,0,0,0,166,169,999,1838,1
2138,1045,3,45,77.3000,1,0,0,100,0,0,...,0,1,0,1,0,911,930,885,526,0

In [4]:
df['cid'].value_counts(normalize=True) * 100

cid
0    75.642824
1    24.357176
Name: proportion, dtype: float64

In [5]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df_scaled = scaler.fit_transform(df)

array([[ 0.2357988 ,  0.42496   ,  1.46454203, ..., -0.87615103,
        -1.37425994, -0.56745262],
       [ 0.42059994,  1.31177897,  2.95759528, ..., -1.23858648,
        -0.83477895,  1.76226168],
       [ 0.28028796,  1.31177897,  1.11999128, ...,  2.24204361,
         2.15259704, -0.56745262],
       ...,
       [ 0.76966875,  0.42496   ,  2.03879328, ...,  0.84229291,
         0.23743952, -0.56745262],
       [-1.4171447 , -1.34867794, -2.44036645, ...,  0.02577167,
         2.02896598,  1.76226168],
       [ 0.5677564 ,  1.31177897,  1.11999128, ..., -0.21168604,
        -0.92019677, -0.56745262]], shape=(2139, 24))

In [6]:
df_scaled = pd.DataFrame(df_scaled)
df_scaled

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,0.235799,0.424960,1.464542,1.107649,-0.303123,-1.396547,-0.388893,0.771836,-0.149888,-1.106116,...,-1.189210,-1.090177,-0.457338,0.575371,-0.754541,0.603131,0.730927,-0.876151,-1.374260,-0.567453
1,0.420600,1.311779,2.957595,-1.936862,-0.303123,-1.396547,-0.388893,-0.923192,-0.149888,0.904064,...,0.840894,1.134907,-0.457338,0.575371,-0.754541,-1.590108,-1.060207,-1.238586,-0.834779,1.762262
2,0.280288,1.311779,1.119991,1.005025,-0.303123,0.716052,2.571400,-0.923192,-0.149888,0.904064,...,0.840894,1.134907,-0.457338,0.575371,1.325309,-0.206680,-0.672935,2.242044,2.152597,-0.567453
3,0.981848,1.311779,1.349692,0.765569,-0.303123,0.716052,-0.388893,0.771836,-0.149888,0.904064,...,0.840894,1.134907,-0.457338,0.575371,-0.754541,-0.535666,0.156934,1.256802,0.068852,-0.567453
4,0.721757,-1.348678,0.890291,-0.636959,-0.303123,0.716052,-0.388893,0.771836,-0.149888,0.904064,...,0.840894,1.134907,-0.457338,-1.738009,-0.754541,1.294845,-0.126605,-0.242930,-0.344750,-0.567453
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2134,0.725180,1.311779,-1.636415,-1.646094,3.298990,-1.396547,-0.388893,0.771836,-0.149888,0.904064,...,0.840894,1.134907,-0.457338,0.575371,1.325309,-1.674463,-1.814005,-0.886566,-0.484116,-0.567453
2135,-1.656702,-1.348678,-2.095816,2.099680,3.298990,-1.396547,-0.388893,0.771836,-0.149888,0.904064,...,0.840894,1.134907,-0.457338,-1.738009,1.325309,0.189790,-1.060207,1.608823,0.212713,-0.567453
2136,0.769669,0.424960,2.038793,-0.397503,3.298990,0.716052,-0.388893,-0.923192,-0.149888,0.904064,...,0.840894,1.134907,-0.457338,0.575371,-0.754541,0.577824,-0.050533,0.842293,0.237440,-0.567453
2137,-1.417145,-1.348678,-2.440366,-1.140667,3.298990,-1.396547,-0.388893,0.771836,-0.149888,-1.106116,...,-1.189210,-1.090177,-0.457338,-1.738009,-0.754541,-1.556366,-1.399071,0.025772,2.028966,1.762262
2138,0.567756,1.311779,1.119991,0.164003,3.298990,-1.396547,-0.388893,0.771836,-0.149888,-1.106116,...,-1.189210,-1.090177,-0.457338,0.575371,-0.754541,4.728107,3.863683,-0.211686,-0.920197,-0.567453

In [14]:
import seaborn as sns
import matplotlib.pyplot as plt

corr = df_scaled.corr()
filtered_corr = corr[(corr > 0.5) | (corr < -0.5)]
filtered_corr

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.574989
1,NaN,1.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.77599,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,1.00000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,...,0.903417,0.848624,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.655054,...,0.680354,0.833213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,0.60782,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.903417,...,1.000000,0.916723,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.848624,...,0.916723,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,0.77599,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.00000,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.000000,0.583578,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.583578,1.000000,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.756218,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.756218,1.000000,NaN
23,-0.574989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000